DROP TABLE IF EXISTS city;
CREATE TABLE city (
  city_id        integer PRIMARY KEY,
  city_name      varchar(50) NOT NULL,
  population     integer     NOT NULL CHECK (population >= 0),
  estimated_rent integer     NOT NULL CHECK (estimated_rent >= 0),
  city_rank      integer     NOT NULL CHECK (city_rank > 0)
);

DROP TABLE IF EXISTS customers  CASCADE;
CREATE TABLE customers (
  customer_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name varchar(100) NOT NULL,
  city_id       integer NOT NULL,
  CONSTRAINT fk_customers_city 
  FOREIGN KEY (city_id) REFERENCES city(city_id) ON DELETE RESTRICT

);

DROP TABLE IF EXISTS products   CASCADE;
CREATE TABLE products (
  product_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name  varchar(200) NOT NULL,
  price         numeric(10,2) NOT NULL CHECK (price >= 0)

);
DROP TABLE IF EXISTS sales      CASCADE;
CREATE TABLE sales (
  sale_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_date   date NOT NULL,
  product_id  integer NOT NULL,
  customer_id integer NOT NULL,
  total       numeric(10,2) NOT NULL CHECK (total >= 0),
  rating      smallint CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT fk_sales_product
    FOREIGN KEY (product_id)  REFERENCES products(product_id)   ON DELETE RESTRICT,
  CONSTRAINT fk_sales_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE RESTRICT

);